services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres@123}
      POSTGRES_DB: eConnectOne
    volumes:
      - 'E:/Docker/wsl/DockerDesktopWSL/econnectone/postgres:/var/lib/postgresql/data'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD:-postgres@123}@postgres:5432/eConnectOne"
      ASPNETCORE_PORT: "10000"
      DOTNET_ENVIRONMENT: Production
    ports:
      - '10000:10000'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - '80:80'

